In [ ]:
# 
# Build pCVR using GAP bigquery and Tensorflow DNN library 
# Used calibration period for training & holdout period for validation
# Script can be run on Compute Engine of GCP
# The query to extract GA360 features referred to an Auto case by Yiling Liu(yilliu@) 
# 
# By JeeWook Kim
#

In [9]:
%%bash
pip install --upgrade pip
pip install tensorflow
pip install --upgrade tensorflow
pip install --upgrade google-api-python-client
pip install --upgrade gcloud


Requirement already up-to-date: pip in /usr/local/lib/python2.7/dist-packages (10.0.1)
Requirement already up-to-date: tensorflow in /usr/local/lib/python2.7/dist-packages (1.9.0)
Requirement not upgraded as not directly required: mock>=2.0.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (2.0.0)
Requirement not upgraded as not directly required: grpcio>=1.8.6 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1.13.0)
Requirement not upgraded as not directly required: termcolor>=1.1.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1.1.0)
Requirement not upgraded as not directly required: numpy>=1.13.3 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1.14.5)
Requirement not upgraded as not directly required: tensorboard<1.10.0,>=1.9.0 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1.9.0)
Requirement not upgraded as not directly required: backports.weakref>=1.0rc1 in /usr/local/lib/python2.7/dist-packages (from tensorflow) (1

google-cloud-resource-manager 0.26.0 has requirement google-cloud-core<0.27dev,>=0.26.0, but you'll have google-cloud-core 0.27.1 which is incompatible.
google-cloud-vision 0.26.0 has requirement google-cloud-core<0.27dev,>=0.26.0, but you'll have google-cloud-core 0.27.1 which is incompatible.
google-cloud-vision 0.26.0 has requirement google-gax<0.16dev,>=0.15.13, but you'll have google-gax 0.12.5 which is incompatible.
google-cloud-monitoring 0.26.0 has requirement google-cloud-core<0.27dev,>=0.26.0, but you'll have google-cloud-core 0.27.1 which is incompatible.
tensorboard 1.9.0 has requirement futures>=3.1.1; python_version < "3", but you'll have futures 3.0.5 which is incompatible.
google-cloud 0.27.0 has requirement google-cloud-core<0.27dev,>=0.26.0, but you'll have google-cloud-core 0.27.1 which is incompatible.
google-cloud 0.27.0 has requirement google-cloud-storage<1.4dev,>=1.3.0, but you'll have google-cloud-storage 1.4.0 which is incompatible.
google-cloud-bigtable 0.26.

In [25]:
from __future__ import absolute_import
from __future__ import division
from __future__ import print_function

import os
import urllib

import numpy as np
import tensorflow as tf
print(tf.__version__)

import datetime
from dateutil.relativedelta import relativedelta

def main():
    # Dataset should look like this 
    training_set_data = np.array([[6.4, 2.8, 5.6, 2.2],
                                [5.,  2.3, 3.3, 1. ],
                                [4.9, 2.5, 4.5, 1.7],
                                [4.9, 3.1, 1.5, 0.1],
                                [5.7, 3.8, 1.7, 0.3],
                                [4.4, 3.2, 1.3, 0.2],
                                [5.4, 3.4, 1.5, 0.4],
                                [6.9, 3.1, 5.1, 2.3],
                                [6.7, 3.1, 4.4, 1.4],
                                [5.1, 3.7, 1.5, 0.4]])
    training_set_target = np.array([2, 1, 2, 0, 0, 0, 0, 2, 1, 0])

    print('# training_set_data')
    print(np.array(training_set_data)[:10])
    print('# training_set_target')
    print(np.array(training_set_target)[:10])

    test_set_data = np.array([[5.9, 3.,  4.2, 1.5],
                            [6.9, 3.1, 5.4, 2.1],
                            [5.1, 3.3, 1.7, 0.5],
                            [6.,  3.4, 4.5, 1.6],
                            [5.5, 2.5, 4.,  1.3],
                            [6.2, 2.9, 4.3, 1.3],
                            [5.5, 4.2, 1.4, 0.2],
                            [6.3, 2.8, 5.1, 1.5],
                            [5.6, 3.,  4.1, 1.3],
                            [6.7, 2.5, 5.8, 1.8]])
    test_set_target = np.array([1, 2, 0, 1, 1, 1, 0, 2, 1, 2])  
    print('# test_set_data')
    print(np.array(test_set_data)[:10])
    print('# test_set_target')
    print(np.array(test_set_target)[:10])

    today = datetime.date.today().strftime("%Y%m%d")
    # calibration begin date => 12 months ago
    begin_date = '20160801'
    # obserbation end date => 3 days ago
    end_date = '20170801'
    # calibration end date => 6 months ago
    # calibration_end_date = (datetime.date.today() + relativedelta(months=-6)).strftime("%Y%m%d")
    calibration_end_date = '20170201'
    # Animals In Space table
    # gap_table = 'google.com:bigquery-150208.90624960.ga_sessions_*'
    # Googel Store demo table
    gap_table = 'bigquery-public-data.google_analytics_sample.ga_sessions_*'


    print('# today: {}'.format(today))
    print('# begin_date: {}'.format(begin_date))
    print('# end_date: {}'.format(end_date))
    print('# calibration_end_date: {}'.format(calibration_end_date))
# query to retrieve GAP exported BigQuery ecommerce tranactions (users with purchases in the calibration period)
    sql_train = """ 
         WITH ga_raw AS (
          SELECT
            date,
            fullVisitorId,
            channelGrouping,
            socialEngagementType,
            visitId,
            visitNumber,
            trafficSource.source,
            trafficSource.medium,
            device.deviceCategory,
            device.browser,
            hits.hitNumber,
            hits.page.pagePath as pagePath,
            hits.type as type,
            hits.eventInfo.eventCategory as eventCategory,
            hits.eventInfo.eventAction as eventAction,
            hits.eventInfo.eventLabel as eventLabel,
            TIMESTAMP_SECONDS(visitStartTime) AS sessionStartTtime, 
            TIMESTAMP_ADD(TIMESTAMP_SECONDS(visitStartTime), INTERVAL hits.time MILLISECOND) AS hitTime,
            CASE WHEN hits.hour IN (5,6,7,8,9,10) THEN 1 ELSE 0 END AS morningVisit,
            CASE WHEN hits.hour IN (11,12,13,14,15,16) THEN 1 ELSE 0 END AS dayVisit,
            CASE WHEN hits.hour IN (17,18,19,20,21,22) THEN 1 ELSE 0 END AS eveningVisit,
            totals.timeOnSite AS timeOnSite,
            totals.bounces AS bounceNumber,
            totals.timeOnScreen	AS timeOnScreen,
            totals.transactions AS transactions,
            IF(REGEXP_CONTAINS(trafficSource.source , 'google') AND REGEXP_CONTAINS(trafficSource.medium , 'cpc'), 1, 0) AS fromPaidSearch,
            IF(REGEXP_CONTAINS(trafficSource.source , 'google') AND REGEXP_CONTAINS(trafficSource.medium , 'organic'), 1, 0) AS fromOrganicSearch
          FROM `"""+gap_table+"""`, unnest(hits) as hits
          WHERE
           (_TABLE_SUFFIX >= '"""+begin_date+"""' AND _TABLE_SUFFIX <= '"""+calibration_end_date+"""') ),
       
        session AS ( -- aggregate hit level to session level
          SELECT fullVisitorId, visitId,
            SUM(if (timeOnSite is null, 0, timeOnSite)) AS timeOnSite,
            SUM(if (bounceNumber is null, 0, bounceNumber)) AS bounceNumber,
            SUM( dayVisit ) AS dayVisit,
            SUM( eveningVisit ) AS eveningVisit ,
            SUM( morningVisit ) AS morningVisit ,
            ANY_VALUE(visitNumber) as visitNumber,

            SUM(if( type = 'PAGE', 1, 0)) as totalPageViews, 
            SUM(if( type = 'EVENT', 1, 0)) as totalEvents, 

            SUM(if(pagePath LIKE '%/apparel%', 1, 0)) as apparelViews,
            SUM(if(pagePath LIKE '%/bags%', 1, 0)) as bagsViews,
            SUM(if(pagePath LIKE '%/drinkware%', 1, 0)) as drinkwareViews,
            SUM(if(pagePath LIKE '%/accessories%', 1, 0)) as accessoriesViews,
            SUM(if(pagePath LIKE '%/office%', 1, 0)) as officeViews,

            IF(SUM(fromPaidSearch) != 0, 1, 0) AS  fromPaidSearch,
            IF(SUM(fromOrganicSearch) != 0, 1, 0) AS  fromOrganicSearch,

            IF(SUM(transactions) is null, False, True) AS hasConverted,

            COUNT(*) as totalInteractions    
          FROM ga_raw
          GROUP BY fullVisitorId , visitId ),
  
       ml_dataset AS ( -- aggregate seesion level data to user level

          SELECT 
            fullVisitorId, 
            MAX(visitNumber) as totalSessions,
            SUM(totalPageViews) as totalPageViews, 
            SUM(totalInteractions) as totalInteractions, 

            SUM(timeOnSite) AS timeOnSite,
            SUM(bounceNumber) AS bounceNumber,
            SUM( dayVisit ) AS dayVisit,
            SUM( eveningVisit ) AS eveningVisit ,
            SUM( morningVisit ) AS morningVisit ,

            SUM(totalEvents) as totalEvents, 

            SUM(apparelViews) as apparelViews,
            SUM(bagsViews) as bagsViews,
            SUM(drinkwareViews)  as drinkwareViews,
            SUM(accessoriesViews) as accessoriesViews,
            SUM(officeViews) as officeViews,

            SUM(fromPaidSearch) AS fromPaidSearch,
            SUM(fromOrganicSearch) AS fromOrganicSearch,
            ANY_VALUE(hasConverted) AS hasConverted

          FROM session
          GROUP BY fullVisitorId)

        select * from ml_dataset; 
    """

    print ('# BigQuery SQL - train data')  
    print (sql_train)
    
    sql_test = """ 
         WITH ga_raw AS (
          SELECT
            date,
            fullVisitorId,
            channelGrouping,
            socialEngagementType,
            visitId,
            visitNumber,
            trafficSource.source,
            trafficSource.medium,
            device.deviceCategory,
            device.browser,
            hits.hitNumber,
            hits.page.pagePath as pagePath,
            hits.type as type,
            hits.eventInfo.eventCategory as eventCategory,
            hits.eventInfo.eventAction as eventAction,
            hits.eventInfo.eventLabel as eventLabel,
            TIMESTAMP_SECONDS(visitStartTime) AS sessionStartTtime, 
            TIMESTAMP_ADD(TIMESTAMP_SECONDS(visitStartTime), INTERVAL hits.time MILLISECOND) AS hitTime,
            CASE WHEN hits.hour IN (5,6,7,8,9,10) THEN 1 ELSE 0 END AS morningVisit,
            CASE WHEN hits.hour IN (11,12,13,14,15,16) THEN 1 ELSE 0 END AS dayVisit,
            CASE WHEN hits.hour IN (17,18,19,20,21,22) THEN 1 ELSE 0 END AS eveningVisit,
            totals.timeOnSite AS timeOnSite,
            totals.bounces AS bounceNumber,
            totals.timeOnScreen	AS timeOnScreen,
            totals.transactions AS transactions,
            IF(REGEXP_CONTAINS(trafficSource.source , 'google') AND REGEXP_CONTAINS(trafficSource.medium , 'cpc'), 1, 0) AS fromPaidSearch,
            IF(REGEXP_CONTAINS(trafficSource.source , 'google') AND REGEXP_CONTAINS(trafficSource.medium , 'organic'), 1, 0) AS fromOrganicSearch
          FROM `"""+gap_table+"""`, unnest(hits) as hits
          WHERE
           (_TABLE_SUFFIX > '"""+calibration_end_date+"""' AND _TABLE_SUFFIX <= '"""+end_date+"""') ),
       
        session AS ( -- aggregate hit level to session level
          SELECT fullVisitorId, visitId,
            SUM(if (timeOnSite is null, 0, timeOnSite)) AS timeOnSite,
            SUM(if (bounceNumber is null, 0, bounceNumber)) AS bounceNumber,
            SUM( dayVisit ) AS dayVisit,
            SUM( eveningVisit ) AS eveningVisit ,
            SUM( morningVisit ) AS morningVisit ,
            ANY_VALUE(visitNumber) as visitNumber,

            SUM(if( type = 'PAGE', 1, 0)) as totalPageViews, 
            SUM(if( type = 'EVENT', 1, 0)) as totalEvents, 

            SUM(if(pagePath LIKE '%/apparel%', 1, 0)) as apparelViews,
            SUM(if(pagePath LIKE '%/bags%', 1, 0)) as bagsViews,
            SUM(if(pagePath LIKE '%/drinkware%', 1, 0)) as drinkwareViews,
            SUM(if(pagePath LIKE '%/accessories%', 1, 0)) as accessoriesViews,
            SUM(if(pagePath LIKE '%/office%', 1, 0)) as officeViews,

            IF(SUM(fromPaidSearch) != 0, 1, 0) AS  fromPaidSearch,
            IF(SUM(fromOrganicSearch) != 0, 1, 0) AS  fromOrganicSearch,

            IF(SUM(transactions) is null, False, True) AS hasConverted,

            COUNT(*) as totalInteractions    
          FROM ga_raw
          GROUP BY fullVisitorId , visitId ),
  
       ml_dataset AS ( -- aggregate seesion level data to user level

          SELECT 
            fullVisitorId, 
            MAX(visitNumber) as totalSessions,
            SUM(totalPageViews) as totalPageViews, 
            SUM(totalInteractions) as totalInteractions, 

            SUM(timeOnSite) AS timeOnSite,
            SUM(bounceNumber) AS bounceNumber,
            SUM( dayVisit ) AS dayVisit,
            SUM( eveningVisit ) AS eveningVisit ,
            SUM( morningVisit ) AS morningVisit ,

            SUM(totalEvents) as totalEvents, 

            SUM(apparelViews) as apparelViews,
            SUM(bagsViews) as bagsViews,
            SUM(drinkwareViews)  as drinkwareViews,
            SUM(accessoriesViews) as accessoriesViews,
            SUM(officeViews) as officeViews,

            SUM(fromPaidSearch) AS fromPaidSearch,
            SUM(fromOrganicSearch) AS fromOrganicSearch,
            ANY_VALUE(hasConverted) AS hasConverted

          FROM session
          GROUP BY fullVisitorId)

        select * from ml_dataset; 
    """

    print ('# BigQuery SQL - test data')  
    print (sql_test)
    
    # execute the query using datalab lib
    import google.datalab.bigquery as bq
    # Pandas lib to handle table data
    import pandas as pd
    transaction_query = bq.Query(sql_train)
    query_result = transaction_query.execute()
    query_data = query_result.result().to_dataframe()
    
    print('# query_data # of converted users {}'.format(query_data[query_data['hasConverted']==True].shape[0]))
    print(query_data[query_data['hasConverted']==True].head(20))
    print('# query_data # of not converted users {}'.format(query_data[query_data['hasConverted']==False].shape[0]))
    print(query_data[query_data['hasConverted']==False].head(20))
    
    training_set_data = query_data.as_matrix(columns=["totalPageViews", "totalInteractions", "timeOnSite","bounceNumber","dayVisit","eveningVisit","morningVisit","totalEvents","apparelViews","bagsViews","drinkwareViews","accessoriesViews","officeViews","fromPaidSearch","fromOrganicSearch"])
    training_set_target = query_data.as_matrix(columns=["hasConverted"])
    
    
    test_transaction_query = bq.Query(sql_test)
    test_query_result = test_transaction_query.execute()
    test_query_data = test_query_result.result().to_dataframe()
    
    
    test_set_data = test_query_data.as_matrix(columns=["totalPageViews", "totalInteractions", "timeOnSite","bounceNumber","dayVisit","eveningVisit","morningVisit","totalEvents","apparelViews","bagsViews","drinkwareViews","accessoriesViews","officeViews","fromPaidSearch","fromOrganicSearch"])
    test_set_target = test_query_data.as_matrix(columns=["hasConverted"])
    
    # Specify that all features have real-value data
    feature_columns = [tf.feature_column.numeric_column("x", shape=[15])]

    # Build 3 layer DNN with 10, 20, 10 units respectively.
    classifier = tf.estimator.DNNClassifier(feature_columns=feature_columns,
                                          hidden_units=[10, 20, 10],
                                          n_classes=2,
                                          model_dir="/tmp/pcvr_model")
    # Define the training inputs
    train_input_fn = tf.estimator.inputs.numpy_input_fn(
      x={"x": np.array(training_set_data)},
      y=np.array(training_set_target),
      num_epochs=None,
      shuffle=True)

    # Train model.
    classifier.train(input_fn=train_input_fn, steps=2000)

    # Define the test inputs
    test_input_fn = tf.estimator.inputs.numpy_input_fn(
      x={"x": np.array(test_set_data)},
      y=np.array(test_set_target),
      num_epochs=1,
      shuffle=False)

    # Evaluate accuracy.
    accuracy_score = classifier.evaluate(input_fn=test_input_fn)["accuracy"]

    print("\nTest Accuracy: {0:f}\n".format(accuracy_score))

    # Classify samples.
    new_samples = np.array(
      [[6.4, 3.2, 4.5, 1.5],
       [5.8, 3.1, 5.0, 1.7]], dtype=np.float32)
    new_samples= test_query_data[query_data['hasConverted']==False].as_matrix(columns=["totalPageViews", "totalInteractions", "timeOnSite","bounceNumber","dayVisit","eveningVisit","morningVisit","totalEvents","apparelViews","bagsViews","drinkwareViews","accessoriesViews","officeViews","fromPaidSearch","fromOrganicSearch"])

    predict_input_fn = tf.estimator.inputs.numpy_input_fn(
      x={"x": new_samples},
      num_epochs=1,
      shuffle=False)

    predictions = list(classifier.predict(input_fn=predict_input_fn))
    
    print("predictions: {}".format(predictions[:10]))
    predicted_classes = [p["classes"] for p in predictions]

    print(
      "New Samples, Class Predictions:    {}\n"
      .format(predicted_classes[:50]))

if __name__ == "__main__":
    main()

1.9.0
# training_set_data
[[6.4 2.8 5.6 2.2]
 [5.  2.3 3.3 1. ]
 [4.9 2.5 4.5 1.7]
 [4.9 3.1 1.5 0.1]
 [5.7 3.8 1.7 0.3]
 [4.4 3.2 1.3 0.2]
 [5.4 3.4 1.5 0.4]
 [6.9 3.1 5.1 2.3]
 [6.7 3.1 4.4 1.4]
 [5.1 3.7 1.5 0.4]]
# training_set_target
[2 1 2 0 0 0 0 2 1 0]
# test_set_data
[[5.9 3.  4.2 1.5]
 [6.9 3.1 5.4 2.1]
 [5.1 3.3 1.7 0.5]
 [6.  3.4 4.5 1.6]
 [5.5 2.5 4.  1.3]
 [6.2 2.9 4.3 1.3]
 [5.5 4.2 1.4 0.2]
 [6.3 2.8 5.1 1.5]
 [5.6 3.  4.1 1.3]
 [6.7 2.5 5.8 1.8]]
# test_set_target
[1 2 0 1 1 1 0 2 1 2]
# today: 20180712
# begin_date: 20160801
# end_date: 20170801
# calibration_end_date: 20170201
# BigQuery SQL - train data
 
         WITH ga_raw AS (
          SELECT
            date,
            fullVisitorId,
            channelGrouping,
            socialEngagementType,
            visitId,
            visitNumber,
            trafficSource.source,
            trafficSource.medium,
            device.deviceCategory,
            device.browser,
            hits.hitNumber,
           

/usr/local/lib/python2.7/dist-packages/ipykernel/__main__.py:320: UserWarning: Boolean Series key will be reindexed to match DataFrame index.


INFO:tensorflow:Calling model_fn.
INFO:tensorflow:Done calling model_fn.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Restoring parameters from /tmp/pcvr_model/model.ckpt-6000
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
predictions: [{'probabilities': array([9.999982e-01, 1.743986e-06], dtype=float32), 'logits': array([-13.2593355], dtype=float32), 'classes': array(['0'], dtype=object), 'class_ids': array([0]), 'logistic': array([1.7439859e-06], dtype=float32)}, {'probabilities': array([9.999957e-01, 4.336254e-06], dtype=float32), 'logits': array([-12.3484955], dtype=float32), 'classes': array(['0'], dtype=object), 'class_ids': array([0]), 'logistic': array([4.336254e-06], dtype=float32)}, {'probabilities': array([9.999957e-01, 4.336254e-06], dtype=float32), 'logits': array([-12.3484955], dtype=float32), 'classes': array(['0'], dtype=object), 'class_ids': array([0]), 'logistic': array([4.336254e-06], dtype=float32)}, {'probabilities': arra